server:
  port: 8089

#项目名  项目规则
config-project:
  projects:
    - name: "ph"
      rule: "091"
      prefix: "http://47.97.198.154:8080/loan"
    - name: "sala"
      rule: "092"
      prefix: "http://47.97.198.154:8081/salafee"

#skypay的key
skypay:
  encryptKey: "38EC73B729254863"